export const currencies = [
  {
    name: "United Arab Emirates Dirham",
    code: "AED",
    countryCode: "AE",
    symbol: "د.إ",
  },
  { name: "Afghanistan Afghani", code: "AFN", countryCode: "AF", symbol: "؋" },
  { name: "Albanian Lek", code: "ALL", countryCode: "AL", symbol: "Lek" },
  { name: "Armenian Dram", code: "AMD", countryCode: "AM", symbol: "֏" },
  {
    name: "Netherlands Antillean Guilder",
    code: "ANG",
    countryCode: "AN",
    symbol: "ƒ",
  },
  { name: "Angolan Kwanza", code: "AOA", countryCode: "AO", symbol: "Kz" },
  { name: "Argentine Peso", code: "ARS", countryCode: "AR", symbol: "$" },
  { name: "Australian Dollar", code: "AUD", countryCode: "AU", symbol: "$" },
  { name: "Aruban Florin", code: "AWG", countryCode: "AW", symbol: "ƒ" },
  { name: "Azerbaijani Manat", code: "AZN", countryCode: "AZ", symbol: "₼" },
  {
    name: "Bosnia and Herzegovina Convertible Mark",
    code: "BAM",
    countryCode: "BA",
    symbol: "KM",
  },
  { name: "Barbadian Dollar", code: "BBD", countryCode: "BB", symbol: "$" },
  { name: "Bangladeshi Taka", code: "BDT", countryCode: "BD", symbol: "৳" },
  { name: "Bulgarian Lev", code: "BGN", countryCode: "BG", symbol: "лв" },
  { name: "Bahraini Dinar", code: "BHD", countryCode: "BH", symbol: ".د.ب" },
  { name: "Burundian Franc", code: "BIF", countryCode: "BI", symbol: "FBu" },
  { name: "Bermudian Dollar", code: "BMD", countryCode: "BM", symbol: "$" },
  { name: "Brunei Dollar", code: "BND", countryCode: "BN", symbol: "$" },
  { name: "Bolivian Boliviano", code: "BOB", countryCode: "BO", symbol: "Bs." },
  { name: "Brazilian Real", code: "BRL", countryCode: "BR", symbol: "R$" },
  { name: "Bahamian Dollar", code: "BSD", countryCode: "BS", symbol: "$" },
  { name: "Bhutanese Chherty", code: "BTN", countryCode: "BT", symbol: "Nu." },
  { name: "Botswana Pula", code: "BWP", countryCode: "BW", symbol: "P" },
  { name: "Belarusian Ruble", code: "BYN", countryCode: "BY", symbol: "Br" },
  { name: "Belize Dollar", code: "BZD", countryCode: "BZ", symbol: "$" },
  { name: "Canadian Dollar", code: "CAD", countryCode: "CA", symbol: "$" },
  { name: "Congolese Franc", code: "CDF", countryCode: "CD", symbol: "FC" },
  { name: "Swiss Franc", code: "CHF", countryCode: "CH", symbol: "CHF" },
  { name: "Chilean Peso", code: "CLP", countryCode: "CL", symbol: "$" },
  { name: "Chinese Yuan", code: "CNY", countryCode: "CN", symbol: "¥" },
  { name: "Colombian Peso", code: "COP", countryCode: "CO", symbol: "$" },
  { name: "Costa Rican Colón", code: "CRC", countryCode: "CR", symbol: "₡" },
  { name: "Cuban Peso", code: "CUP", countryCode: "CU", symbol: "$" },
  {
    name: "Cape Verdean Escudo",
    code: "CVE",
    countryCode: "CV",
    symbol: "Esc",
  },
  { name: "Czech Koruna", code: "CZK", countryCode: "CZ", symbol: "Kč" },
  { name: "Djiboutian Franc", code: "DJF", countryCode: "DJ", symbol: "Fdj" },
  { name: "Danish Krone", code: "DKK", countryCode: "DK", symbol: "kr" },
  { name: "Dominican Peso", code: "DOP", countryCode: "DO", symbol: "$" },
  { name: "Algerian Dinar", code: "DZD", countryCode: "DZ", symbol: "د.ج" },
  { name: "Egyptian Pound", code: "EGP", countryCode: "EG", symbol: "£" },
  { name: "Eritrean Nakfa", code: "ERN", countryCode: "ER", symbol: "Nfk" },
  { name: "Ethiopian Birr", code: "ETB", countryCode: "ET", symbol: "Br" },
  { name: "Euro", code: "EUR", countryCode: "EU", symbol: "€" },
  { name: "Fijian Dollar", code: "FJD", countryCode: "FJ", symbol: "$" },
  {
    name: "Falkland Islands Pound",
    code: "FKP",
    countryCode: "FK",
    symbol: "£",
  },
  {
    name: "British Pound Sterling",
    code: "GBP",
    countryCode: "GB",
    symbol: "£",
  },
  { name: "Georgian Lari", code: "GEL", countryCode: "GE", symbol: "ლ" },
  { name: "Guernsey Pound", code: "GGP", countryCode: "GG", symbol: "£" },
  { name: "Ghanaian Cedi", code: "GHS", countryCode: "GH", symbol: "₵" },
  { name: "Gibraltar Pound", code: "GIP", countryCode: "GI", symbol: "£" },
  { name: "Gambian Dalasi", code: "GMD", countryCode: "GM", symbol: "D" },
  { name: "Guinean Franc", code: "GNF", countryCode: "GN", symbol: "FG" },
  { name: "Guatemalan Quetzal", code: "GTQ", countryCode: "GT", symbol: "Q" },
  { name: "Guyanese Dollar", code: "GYD", countryCode: "GY", symbol: "$" },
  { name: "Hong Kong Dollar", code: "HKD", countryCode: "HK", symbol: "$" },
  { name: "Honduran Lempira", code: "HNL", countryCode: "HN", symbol: "L" },
  { name: "Croatian Kuna", code: "HRK", countryCode: "HR", symbol: "kn" },
  { name: "Haitian Gourde", code: "HTG", countryCode: "HT", symbol: "G" },
  { name: "Hungarian Forint", code: "HUF", countryCode: "HU", symbol: "Ft" },
  { name: "Indonesian Rupiah", code: "IDR", countryCode: "ID", symbol: "Rp" },
  { name: "Israeli Shekel", code: "ILS", countryCode: "IL", symbol: "₪" },
  { name: "Manx Pound", code: "IMP", countryCode: "IM", symbol: "£" },
  { name: "Indian Rupee", code: "INR", countryCode: "IN", symbol: "₹" },
  { name: "Iraqi Dinar", code: "IQD", countryCode: "IQ", symbol: "ع.د" },
  { name: "Iranian Rial", code: "IRR", countryCode: "IR", symbol: "ریال" },
  { name: "Icelandic Króna", code: "ISK", countryCode: "IS", symbol: "kr" },
  { name: "Jersey Pound", code: "JEP", countryCode: "JE", symbol: "£" },
  { name: "Jamaican Dollar", code: "JMD", countryCode: "JM", symbol: "$" },
  { name: "Jordanian Dinar", code: "JOD", countryCode: "JO", symbol: "د.أ" },
  { name: "Japanese Yen", code: "JPY", countryCode: "JP", symbol: "¥" },
  { name: "Kenyan Shilling", code: "KES", countryCode: "KE", symbol: "KSh" },
  { name: "Kyrgyzstani Som", code: "KGS", countryCode: "KG", symbol: "сом" },
  { name: "Cambodian Riel", code: "KHR", countryCode: "KH", symbol: "៛" },
  { name: "Kiribati Dollar", code: "KID", countryCode: "KI", symbol: "$" },
  { name: "Comorian Franc", code: "KMF", countryCode: "KM", symbol: "FC" },
  { name: "North Korean Won", code: "KPW", countryCode: "KP", symbol: "₩" },
  { name: "South Korean Won", code: "KRW", countryCode: "KR", symbol: "₩" },
  { name: "Kuwaiti Dinar", code: "KWD", countryCode: "KW", symbol: "د.ك" },
  {
    name: "Cayman Islands Dollar",
    code: "KYD",
    countryCode: "KY",
    symbol: "$",
  },
  { name: "Kazakhstani Tenge", code: "KZT", countryCode: "KZ", symbol: "₸" },
  { name: "Laotian Kip", code: "LAK", countryCode: "LA", symbol: "₭" },
  { name: "Lebanese Pound", code: "LBP", countryCode: "LB", symbol: "ل.ل" },
  { name: "Sri Lankan Rupee", code: "LKR", countryCode: "LK", symbol: "₨" },
  { name: "Liberian Dollar", code: "LRD", countryCode: "LR", symbol: "$" },
  { name: "Lesotho Loti", code: "LSL", countryCode: "LS", symbol: "L" },
  { name: "Libyan Dinar", code: "LYD", countryCode: "LY", symbol: "ل.د" },
  { name: "Moroccan Dirham", code: "MAD", countryCode: "MA", symbol: "د.م." },
  { name: "Moldovan Leu", code: "MDL", countryCode: "MD", symbol: "L" },
  { name: "Malagasy Ariary", code: "MGA", countryCode: "MG", symbol: "Ar" },
  { name: "Macedonian Denar", code: "MKD", countryCode: "MK", symbol: "ден" },
  { name: "Myanmar Kyat", code: "MMK", countryCode: "MM", symbol: "K" },
  { name: "Mongolian Tögrög", code: "MNT", countryCode: "MN", symbol: "₮" },
  { name: "Macanese Pataca", code: "MOP", countryCode: "MO", symbol: "P" },
  {
    name: "Mauritanian Ouguiya",
    code: "MRO",
    countryCode: "MR",
    symbol: "ع.و",
  },
  { name: "Mauritian Rupee", code: "MUR", countryCode: "MU", symbol: "₨" },
  { name: "Maldivian Rufiyaa", code: "MVR", countryCode: "MV", symbol: "Rf" },
  { name: "Malawian Kwacha", code: "MWK", countryCode: "MW", symbol: "MK" },
  { name: "Mexican Peso", code: "MXN", countryCode: "MX", symbol: "$" },
  { name: "Malaysian Ringgit", code: "MYR", countryCode: "MY", symbol: "RM" },
  { name: "Mozambican Metical", code: "MZN", countryCode: "MZ", symbol: "MT" },
  { name: "Namibian Dollar", code: "NAD", countryCode: "NA", symbol: "$" },
  { name: "Nigerian Naira", code: "NGN", countryCode: "NG", symbol: "₦" },
  { name: "Nicaraguan Córdoba", code: "NIO", countryCode: "NI", symbol: "C$" },
  { name: "Norwegian Krone", code: "NOK", countryCode: "NO", symbol: "kr" },
  { name: "Nepalese Rupee", code: "NPR", countryCode: "NP", symbol: "₨" },
  { name: "New Zealand Dollar", code: "NZD", countryCode: "NZ", symbol: "$" },
  { name: "Omani Rial", code: "OMR", countryCode: "OM", symbol: "ر.ع." },
  { name: "Panamanian Balboa", code: "PAB", countryCode: "PA", symbol: "B/." },
  { name: "Peruvian Sol", code: "PEN", countryCode: "PE", symbol: "S/." },
  {
    name: "Papua New Guinean Kina",
    code: "PGK",
    countryCode: "PG",
    symbol: "K",
  },
  { name: "Philippine Peso", code: "PHP", countryCode: "PH", symbol: "₱" },
  { name: "Pakistani Rupee", code: "PKR", countryCode: "PK", symbol: "₨" },
  { name: "Polish Złoty", code: "PLN", countryCode: "PL", symbol: "zł" },
  { name: "Paraguayan Guarani", code: "PYG", countryCode: "PY", symbol: "Gs" },
  { name: "Qatari Riyal", code: "QAR", countryCode: "QA", symbol: "ر.ق" },
  { name: "Romanian Leu", code: "RON", countryCode: "RO", symbol: "lei" },
  { name: "Serbian Dinar", code: "RSD", countryCode: "RS", symbol: "дин" },
  { name: "Russian Ruble", code: "RUB", countryCode: "RU", symbol: "₽" },
  { name: "Rwandan Franc", code: "RWF", countryCode: "RW", symbol: "FRw" },
  { name: "Saudi Riyal", code: "SAR", countryCode: "SA", symbol: "ر.س" },
  {
    name: "Solomon Islands Dollar",
    code: "SBD",
    countryCode: "SB",
    symbol: "$",
  },
  { name: "Seychellois Rupee", code: "SCR", countryCode: "SC", symbol: "₨" },
  { name: "Sudanese Pound", code: "SDG", countryCode: "SD", symbol: "ج.س." },
  { name: "Swedish Krona", code: "SEK", countryCode: "SE", symbol: "kr" },
  { name: "Singapore Dollar", code: "SGD", countryCode: "SG", symbol: "$" },
  { name: "Saint Helena Pound", code: "SHP", countryCode: "SH", symbol: "£" },
  {
    name: "Sierra Leonean Leone",
    code: "SLL",
    countryCode: "SL",
    symbol: "Le",
  },
  { name: "Somali Shilling", code: "SOS", countryCode: "SO", symbol: "Sh" },
  { name: "Surinamese Dollar", code: "SRD", countryCode: "SR", symbol: "$" },
  { name: "South Sudanese Pound", code: "SSP", countryCode: "SS", symbol: "£" },
  {
    name: "São Tomé and Principe Dobra",
    code: "STN",
    countryCode: "ST",
    symbol: "Db",
  },
  { name: "Syrian Pound", code: "SYP", countryCode: "SY", symbol: "£" },
  { name: "Swazi Lilangeni", code: "SZL", countryCode: "SZ", symbol: "L" },
  { name: "Thai Baht", code: "THB", countryCode: "TH", symbol: "฿" },
  { name: "Tajikistani Somoni", code: "TJS", countryCode: "TJ", symbol: "ЅМ" },
  { name: "Turkmenistan Manat", code: "TMT", countryCode: "TM", symbol: "m" },
  { name: "Tunisian Dinar", code: "TND", countryCode: "TN", symbol: "د.ت" },
  { name: "Tongan Paʻanga", code: "TOP", countryCode: "TO", symbol: "T$" },
  { name: "Turkish Lira", code: "TRY", countryCode: "TR", symbol: "₺" },
  {
    name: "Trinidad and Tobago Dollar",
    code: "TTD",
    countryCode: "TT",
    symbol: "$",
  },
  { name: "Tuvaluan Dollar", code: "TVD", countryCode: "TV", symbol: "$" },
  { name: "New Taiwan Dollar", code: "TWD", countryCode: "TW", symbol: "NT$" },
  { name: "Tanzanian Shilling", code: "TZS", countryCode: "TZ", symbol: "TSh" },
  { name: "Ukrainian Hryvnia", code: "UAH", countryCode: "UA", symbol: "₴" },
  { name: "Ugandan Shilling", code: "UGX", countryCode: "UG", symbol: "USh" },
  { name: "United States Dollar", code: "USD", countryCode: "US", symbol: "$" },
  { name: "Uruguayan Peso", code: "UYU", countryCode: "UY", symbol: "$" },
  { name: "Uzbekistan Som", code: "UZS", countryCode: "UZ", symbol: "so'm" },
  { name: "Venezuelan Bolivar", code: "VEF", countryCode: "VE", symbol: "Bs" },
  { name: "Vietnamese Dong", code: "VND", countryCode: "VN", symbol: "₫" },
  { name: "Vanuatu Vatu", code: "VUV", countryCode: "VU", symbol: "VT" },
  { name: "Samoan Tala", code: "WST", countryCode: "WS", symbol: "WS$" },
  {
    name: "Central African CFA Franc",
    code: "XAF",
    countryCode: "CF",
    symbol: "FCFA",
  },
  {
    name: "East Caribbean Dollar",
    code: "XCD",
    countryCode: "AG",
    symbol: "$",
  },
  {
    name: "Special Drawing Rights",
    code: "XDR",
    countryCode: "--",
    symbol: "SDR",
  },
  {
    name: "West African CFA Franc",
    code: "XOF",
    countryCode: "BJ",
    symbol: "FCFA",
  },
  { name: "CFP Franc", code: "XPF", countryCode: "PF", symbol: "FCFP" },
  { name: "Yemeni Rial", code: "YER", countryCode: "YE", symbol: "ر.ي" },
  { name: "South African Rand", code: "ZAR", countryCode: "ZA", symbol: "R" },
  { name: "Zambian Kwacha", code: "ZMW", countryCode: "ZM", symbol: "ZK" },
  { name: "Zimbabwean Dollar", code: "ZWL", countryCode: "ZW", symbol: "$" },
];
